name: Build & Deploy
on:
    push:
      branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
        steps:
          - name: Deploy Traintime
            uses: appleboy/ssh-action@v0.1.2
            with:
              host: ${{secrets.SSH_HOST}}
              key: ${{secrets.SSH_KEY}}
              username: ${{ secrets.SSH_USERNAME }}

              script: |
                mkdir /var/www/projects.santtuhaltsonen.fi/Traintime
                cd /var/www/projects.santtuhaltsonen.fi/Traintime
                git clone git@github.com:sanntn/Traintime.git
                echo 'Deployment succesfull to Droplet'