name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Traintime
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          
     
          script: |
            mkdir test 
            cd test 
            git clone git@github.com:sanntn/Traintime.git
            echo 'Deployment successful to digital ocean' 
