name: Build & Deploy
on:
    push:
      branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Traintime
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

          script: |
            mkdir /var/www/projects.santtuhaltsonen.fi/Traintime
            cd /var/www/projects.santtuhaltsonen.fi/Traintime
            git clone git@github.com:sanntn/Traintime.git
            echo 'Deployment succesful to Droplet'
            
